# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Merge integration

on:
  pull_request:
    branches: 
    - master
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm ci
    - run: npm run lint
 
  test: 
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm test
      env:
        CI: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  prep:
    needs:
    - lint

    if: github.actor == 'phish108' || startsWith(github.actor, 'dependabot')
    runs-on: ubuntu-latest

    steps:
    - name: check changes
      id: release
      uses: phish108/release-check@main
      with:
        protected-paths: | 
          README.md
          .eslintrc
          LICENSE
          action.yml

  merge: 
    needs: 
    - prep
    - test
    if: github.actor == 'phish108' ||  startsWith(github.actor, 'dependabot')
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo "nothing to do"
    # - name: automerge
    #   uses: "pascalgn/automerge-action@v0.13.0"
    #  env:
    #    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    #    MERGE_LABELS: ""

  build:
    needs:
    - merge

    if: github.actor == 'phish108' || startsWith(github.actor, 'dependabot')
    runs-on: ubuntu-latest

    steps:
    - name: check changes
      id: release
      uses: phish108/release-check@1.0.9
      with:
        protected-paths: | 
          README.md
          .eslintrc
          LICENSE
          action.yml

    - uses: actions/checkout@v2
    - run: |
        git config --local user.email "cpglahn@gmail.com"
        git config --local user.name "Christian Glahn"
        
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    
    - run: | 
        npm ci
        npm run package
        git commit -m "updated package file for $GITSHA" -a 
      if: ${{ steps.release.outputs.proceed == 'true' }}
      env:
        GITSHA: ${{ github.sha }}

    - name: Push changes
      if: ${{ steps.release.outputs.proceed }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
  
  release:
    needs: build

    if: github.actor == 'phish108' || startsWith(github.actor, 'dependabot')
    runs-on: ubuntu-latest

    steps:
    - name: check changes
      id: release
      uses: phish108/release-check@1.0.9
      with:
        protected-paths: | 
          README.md
          .eslintrc
          LICENSE
          action.yml

    - name: check changes MAIN
      id: releaseMain
      uses: phish108/release-check@main
      with:
        protected-paths: | 
          README.md
          .eslintrc
          LICENSE
          action.yml

    - id: tagger
      if: ${{ steps.release.outputs.proceed == 'true' && steps.releaseMain.outputs.proceed == 'true' }}
      uses: phish108/autotag-action@1.1.31
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        dry-run: 'TRUE'

    - uses: actions/checkout@v2

    - run: |
        git config --local user.email "cpglahn@gmail.com"
        git config --local user.name "Christian Glahn"

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    
    - run: | 
        git pull origin
        npm ci
        npm --no-git-tag-version --allow-same-version version ${{ steps.tagger.outputs.new-tag }} 
        sed -ire "s/phish108\/release-check@[0-9]*\.[0-9]*\.[0-9]*/phish108\/release-check@${{ steps.tagger.outputs.new-tag }}/g" README.md
        git commit -m "updated release files for $GITSHA" -a 
      if: ${{ steps.release.outputs.proceed == 'true' && steps.releaseMain.outputs.proceed == 'true' }}
      env:
        GITSHA: ${{ github.sha }}

    - name: Push changes
      if: ${{ steps.release.outputs.proceed == 'true'  && steps.releaseMain.outputs.proceed == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - uses: phish108/autotag-action@1.1.31
      if: ${{ steps.release.outputs.proceed == 'true' && steps.releaseMain.outputs.proceed == 'true'  }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
